name: base
channels:
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _r-mutex=1.0.0
  - alabaster=0.7.12
  - anaconda=2018.12
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.6
  - anaconda-project=0.8.2
  - asn1crypto=0.24.0
  - astroid=2.1.0
  - astropy=3.1
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - babel=2.6.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.3
  - bitarray=0.8.3
  - bkcharts=0.2
  - blas=1.0
  - blaze=0.11.3
  - bleach=3.0.2
  - blosc=1.14.4
  - bokeh=1.0.2
  - boto=2.49.0
  - bottleneck=1.2.1
  - bwidget=1.9.11
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=0.6.1
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.6.8
  - conda-build=3.17.6
  - conda-env=2.6.0
  - conda-verify=3.1.1
  - contextlib2=0.5.5
  - cryptography=2.4.2
  - curl=7.63.0
  - cycler=0.10.0
  - cyrus-sasl=2.1.26
  - cython=0.29.2
  - cytoolz=0.9.0.1
  - dask=1.0.0
  - dask-core=1.0.0
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.3.0
  - defusedxml=0.5.0
  - distributed=1.25.1
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.0.2
  - filelock=3.0.10
  - flask=1.0.2
  - flask-cors=3.0.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.0
  - fonts-anaconda=1
  - freetype=2.9.1
  - fribidi=1.0.5
  - future=0.17.1
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=1.3.7
  - glib=2.56.2
  - glob2=0.6
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.13
  - greenlet=0.4.15
  - gsl=2.4
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.4.1
  - imagesize=1.1.0
  - importlib_metadata=0.6
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - isort=4.3.4
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4
  - jedi=0.13.2
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=0.35.3
  - jupyterlab_server=0.2.0
  - keyring=17.0.0
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libarchive=3.3.3
  - libcurl=7.63.0
  - libdb=6.1.26
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - liblief=0.9.0
  - libntlm=1.4
  - libpng=1.6.35
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.26.0
  - locket=0.2.0
  - lxml=4.2.5
  - lz4-c=1.8.1.2
  - lzo=2.10
  - make=4.2.1
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.1
  - mkl-service=1.1.2
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - more-itertools=4.3.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-python=0.5.6
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.2
  - nltk=3.4
  - nose=1.3.7
  - notebook=5.7.4
  - numba=0.41.0
  - numexpr=2.6.8
  - numpy=1.15.4
  - numpy-base=1.15.4
  - numpydoc=0.8.0
  - odo=0.5.1
  - olefile=0.46
  - openpyxl=2.5.12
  - openssl=1.1.1a
  - packaging=18.0
  - pandas=0.23.4
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.3.1
  - partd=0.3.9
  - path.py=11.5.0
  - pathlib2=2.3.3
  - patsy=0.5.1
  - pcre=8.42
  - pep8=1.7.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pkginfo=1.4.2
  - pluggy=0.8.0
  - ply=3.11
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - psutil=5.4.8
  - ptyprocess=0.6.0
  - py=1.7.0
  - py-lief=0.9.0
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.0.0
  - pygments=2.3.1
  - pylint=2.2.2
  - pyodbc=4.0.25
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytables=3.4.4
  - pytest=4.0.2
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.2.0
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - python=3.7.1
  - python-dateutil=2.7.5
  - python-libarchive-c=2.8
  - python-louvain=0.13
  - pytz=2018.7
  - pywavelets=1.0.1
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtawesome=0.5.3
  - qtconsole=4.4.3
  - qtpy=1.5.2
  - r-assertthat=0.2.0
  - r-backports=1.1.2
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-bh=1.66.0_1
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-broom=0.5.0
  - r-catools=1.17.1.1
  - r-cellranger=1.1.0
  - r-cli=1.0.0
  - r-config=0.3
  - r-crayon=1.3.4
  - r-curl=3.2
  - r-dbi=1.0.0
  - r-dbplyr=1.2.2
  - r-digest=0.6.15
  - r-dplyr=0.7.6
  - r-evaluate=0.11
  - r-fansi=0.2.3
  - r-forcats=0.3.0
  - r-glue=1.3.0
  - r-haven=1.1.2
  - r-highr=0.7
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.2
  - r-httpuv=1.4.5
  - r-httr=1.3.1
  - r-jsonlite=1.5
  - r-knitr=1.20
  - r-later=0.7.3
  - r-lattice=0.20_35
  - r-lazyeval=0.2.1
  - r-magrittr=1.5
  - r-markdown=0.8
  - r-mime=0.5
  - r-miniui=0.1.1.1
  - r-mongolite=1.6
  - r-nlme=3.1_137
  - r-odbc=1.1.5
  - r-openssl=1.0.2
  - r-packrat=0.4.9_3
  - r-pillar=1.3.0
  - r-pkgconfig=2.0.1
  - r-pki=0.1_5.1
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-profvis=0.3.5
  - r-promises=1.0.1
  - r-purrr=0.2.5
  - r-r6=2.2.2
  - r-rappdirs=0.3.1
  - r-rcpp=0.12.18
  - r-rcurl=1.95_4.11
  - r-readr=1.1.1
  - r-readxl=1.1.0
  - r-rematch=1.0.1
  - r-reshape2=1.4.3
  - r-rjava=0.9_10
  - r-rjdbc=0.2_7.1
  - r-rjsonio=1.3_0
  - r-rlang=0.2.1
  - r-rmarkdown=1.10
  - r-rprojroot=1.3_2
  - r-rsconnect=0.8.8
  - r-rstudioapi=0.7
  - r-shiny=1.1.0
  - r-sourcetools=0.1.7
  - r-sparklyr=0.8.4
  - r-stringi=1.2.4
  - r-stringr=1.3.1
  - r-tibble=1.4.2
  - r-tidyr=0.8.1
  - r-tidyselect=0.2.4
  - r-tinytex=0.6
  - r-utf8=1.1.4
  - r-withr=2.1.2
  - r-xfun=0.3
  - r-xml2=1.2.0
  - r-xtable=1.8_2
  - r-yaml=2.2.0
  - readline=7.0
  - requests=2.21.0
  - rope=0.11.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.14.1
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - snowballstemmer=1.2.1
  - sortedcollections=1.0.1
  - sortedcontainers=2.1.0
  - sphinx=1.8.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.2
  - spyder-kernels=0.3.0
  - sqlalchemy=1.2.15
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - sympy=1.3
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tktable=2.10
  - toolz=0.9.0
  - tornado=5.1.1
  - tqdm=4.28.1
  - traitlets=4.3.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.7
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - wurlitzer=1.0.2
  - xlrd=1.2.0
  - xlsxwriter=1.1.2
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - community==1.0.0b1
    - pip==19.0.3
    - setuptools==40.8.0
prefix: /Users/gracer/anaconda3
